# config.yaml

model:
  save_path: "models/saved_model.pkl"  # Path to the trained machine learning model

server:
  host: "0.0.0.0"  # Host IP address for the Flask server
  port: 5000  # Port number for the Flask server








